🏳️
dorianmariefr/nevereatalone pull request #1
Opened 2020-11-14 19:16 UTC by LaurieAnnieClemence

2020-11-14 21:27 UTC, dorianmariefr requested changes
good idea, would be nice to have dedicated page for each blog post so we can link to it for instance.

also blog posts should be public i think, we would need to discuss the interface for that

2020-11-14 21:27 UTC, dorianmariefr commented on app/controllers/posts_controller.rb
> +      redirect_back fallback_location: root_path
(should redirect to the post)

2020-11-14 21:27 UTC, dorianmariefr commented on app/controllers/posts_controller.rb
> +    params.require(:post).permit(:title, :content, :user_id)
no user_id in permitted params, that's a security risk, any user could impersonate any other user

2020-11-14 21:27 UTC, dorianmariefr commented on app/controllers/posts_controller.rb
> +  protected
I prefer private because it's not inherited anywhere.

and with an extra newline after the private

2020-11-14 21:27 UTC, dorianmariefr commented on app/controllers/posts_controller.rb
> +      redirect_to root_url
should redirect to posts index

2020-11-14 21:27 UTC, dorianmariefr commented on app/controllers/posts_controller.rb
> +    @posts = Post.all
should have posts with `order(created_at: :desc)` so that recent posts are on top

2020-11-14 21:27 UTC, dorianmariefr commented on app/helpers/posts_helper.rb
> +end
should be removed if it's empty

2020-11-14 21:27 UTC, dorianmariefr commented on app/controllers/posts_controller.rb
> +
no need for extra newline

2020-11-14 21:27 UTC, dorianmariefr commented on app/models/post.rb
> +  validates :user_id, presence: true
no need, belongs_to already validates the presence of the user

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/layouts/_desktop_navbar.html.slim
> +          => fa("columns")
should use `sticky-note`, i think that's what better fits the blog posts

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/layouts/_desktop_navbar.html.slim
> +          ' Vos idée de recette!
doesn't fit in the menu:

<img width="707" alt="Screenshot 2020-11-14 at 22 07 01" src="https://user-images.githubusercontent.com/58794487/99157023-fa055b80-26c5-11eb-8497-a1efb54c909a.png">

Should just be "Blog" instead of recipes, it will be filled with recipes, but let's keep it a generic blog so that other kinds of content can be posted, e.g. i could posts updates about the site

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/layouts/_mobile_navbar.html.slim
> +        ' Vos idées de recette!
same, `sticky-note` and `Blog`

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/pages/home.html.slim
> +
no need for a giant button on the homepage, let's keep it simple, you can remove this

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/pages/home.html.slim
> +      = link_to "Partages tes idées de recette pendant le confinement !", posts_path, class: "button button--primary button--large"
same, to be removed

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/_form.html.slim
> +  = form_for @post, url: {action: "create"}, html: {class: "nifty_form"} do |f|
only `form_for @post` is needed, also could you unindent the whole file to start at the first column

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/_form.html.slim
> +    = f.hidden_field :user_id, value: current_user.id
that's not the secure way to do it, see controller comments

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/_form.html.slim
> +      br
instead of having `br`, you should have separate `p` (e.g. add two more `p`), and also add some spacing between the `p`  (newlines)

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/_form.html.slim
> +      ' Nom de la recette ?
should be `De quoi veux-tu parler ?`

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/_form.html.slim
> +      ' Alors c'est quoi la recette ?
should be `Qu'est-ce que tu veux dire ?`

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/_form.html.slim
> +    p.mb-4= f.submit "partager ma recette", class: "button--primary"
should be `Ajouter un article`

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/index.html.slim
> +.max-w-2xl.mx-auto.px-4
missing the title, e.g. `- title "Blog"`

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/index.html.slim
> +  h1.text-lg.mb-4.font-bold Vos idées de recettes
should be `Articles`

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/index.html.slim
> +  - if current_user
`if can? :create, Post`

2020-11-14 21:27 UTC, dorianmariefr commented on app/views/posts/index.html.slim
> +      b= link_to post.user, user_path(post.user)
should be something like:

```slim
p.font-bold.mb-4= post.title
.base= markdown(post.content)
p.font-bold.mb-4= link_to post.user.first_name, post.user, class: "text-underline"
```

adds an underline to the link and let users have newlines and lists for instance in their posts

2020-11-14 21:27 UTC, dorianmariefr commented on db/seeds.rb
> +Post.create(title: "Patate douce au lait de coco", content: "Dans 1 cocotte minute mettre : POIX CHICHES DÉTREMPÉS (à faire tremper la veille dans de l'eau ;) + patates douce + oignon + ail + gingemb
you can remove the file, it doesn't work if there is no user named Laurie.

would be nice to have proper seed file, this can be a separate pull request

2020-11-14 21:27 UTC, dorianmariefr commented
also a pull request title and description helps

2020-11-14 21:33 UTC, LaurieAnnieClemence commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: https://sass-lang.com/
ok

2020-11-14 21:37 UTC, LaurieAnnieClemence commented on app/controllers/posts_controller.rb
> +  skip_authorization_check
why?

2020-11-14 21:38 UTC, LaurieAnnieClemence commented on app/controllers/posts_controller.rb
> +      flash[:alert] = @post.errors_to_sentence
ok

2020-11-14 21:40 UTC, LaurieAnnieClemence commented on app/controllers/posts_controller.rb
> +
ok

2020-11-14 21:42 UTC, LaurieAnnieClemence commented on app/controllers/posts_controller.rb
> +      flash[:sucess] = "merci pour la recette ;)"
ok, redirection is good

2020-11-14 21:44 UTC, LaurieAnnieClemence commented on app/views/posts/index.html.slim
> +.max-w-2xl.mx-auto.px-4
ok (  i don't understand utility ?)

2020-11-14 21:46 UTC, LaurieAnnieClemence commented on app/views/posts/index.html.slim
> +  - if current_user
ok

2020-11-14 21:46 UTC, LaurieAnnieClemence commented on app/views/posts/index.html.slim
> +      b= link_to post.user, user_path(post.user)
ok

2020-11-14 21:47 UTC, LaurieAnnieClemence commented on app/views/posts/index.html.slim
> +  h1.text-lg.mb-4.font-bold Vos idées de recettes
ok 👍

2020-11-14 22:56 UTC, LaurieAnnieClemence commented on app/views/posts/index.html.slim
> +  h1.text-lg.mb-4.font-bold Vos idées de recettes
"Recettes" maybe for people understand directly?

2020-11-15 12:28 UTC, dorianmariefr commented on app/controllers/posts_controller.rb
> +  skip_authorization_check
that's how authorizations are handled, e.g. who can do what.

you will need to add something like:

```ruby

can :read, Post

can :manage, Post, user_id: user.id
```

2020-11-15 12:29 UTC, dorianmariefr commented on app/views/posts/index.html.slim
> +.max-w-2xl.mx-auto.px-4
it's the title of the page, e.g. what appears in your chrome tab

2020-11-15 12:30 UTC, dorianmariefr commented on app/views/posts/index.html.slim
> +  h1.text-lg.mb-4.font-bold Vos idées de recettes
should not only be recipes, maybe you can add categories, and add a recipes category?

2020-11-21 19:54 UTC, dorianmariefr commented on app/views/layouts/_desktop_navbar.html.slim
> +          ' Recettes
The name is "Blog" not "Recettes", recettes would be a category

2020-12-13 16:08 UTC, merged

2020-12-13 16:09 UTC, dorianmariefr commented
Merged by #2